<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="XssEvaluationException unit test" tests="4" skipped="0" failures="0" errors="0" timestamp="2020-09-14T14:07:37" hostname="PCSE07195" time="0.015">
  <properties/>
  <testcase name="messageConstructor_ValidMessage_MessageIncluded()" classname="org.owasp.securityshepherd.test.exception.XssEvaluationExceptionTest" time="0.005"/>
  <testcase name="messageExceptionConstructor_ValidMessageAndException_MessageIncluded()" classname="org.owasp.securityshepherd.test.exception.XssEvaluationExceptionTest" time="0.003"/>
  <testcase name="exceptionConstructor_ValidException_MessageIncluded()" classname="org.owasp.securityshepherd.test.exception.XssEvaluationExceptionTest" time="0.002"/>
  <testcase name="noArgsConstructor_NoArguments_ReturnsException()" classname="org.owasp.securityshepherd.test.exception.XssEvaluationExceptionTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
